
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scaling.prescale.com
  resources:
  - clusterscalingstatedefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scaling.prescale.com
  resources:
  - clusterscalingstatedefinitions/finalizers
  verbs:
  - update
- apiGroups:
  - scaling.prescale.com
  resources:
  - clusterscalingstatedefinitions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scaling.prescale.com
  resources:
  - clusterscalingstates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scaling.prescale.com
  resources:
  - clusterscalingstates/finalizers
  verbs:
  - update
- apiGroups:
  - scaling.prescale.com
  resources:
  - clusterscalingstates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scaling.prescale.com
  resources:
  - scalingstates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scaling.prescale.com
  resources:
  - scalingstates/finalizers
  verbs:
  - update
- apiGroups:
  - scaling.prescale.com
  resources:
  - scalingstates/status
  verbs:
  - get
  - patch
  - update
