# permissions for end users to view triggerscalings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: triggerscaling-viewer-role
rules:
- apiGroups:
  - scaling.example.com
  resources:
  - triggerscalings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scaling.example.com
  resources:
  - triggerscalings/status
  verbs:
  - get
