# permissions for end users to edit triggerscalings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: triggerscaling-editor-role
rules:
- apiGroups:
  - scaling.example.com
  resources:
  - triggerscalings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scaling.example.com
  resources:
  - triggerscalings/status
  verbs:
  - get
